### ISSUE TITLE
require> params option behavior

### ISSUE THREAD

**Issue by hiroyuki-sato** [treasure-data/digdag#1180]
@yoyama, @muga Could you confirm `require>` behavior?

Please see [original post](https://twitter.com/sgswtky/status/1151392328227049472?s=20)

Does the following description is correct?
If so, I'll create PR. Because I don't find any description of this option.

`require>` operator doesn't pass a parameter to child task. If you want to set it, use `params` options like the following.

```yaml
+example:
  require>: child
  params:
    param_name1: ${parent_param_name}
```

[Sample workflow](https://github.com/hiroyuki-sato/digdag-support/tree/master/2019-07-17_twitter_require_params)
