### ISSUE TITLE
support Podman 

### ISSUE THREAD

**Issue by thejeshgn** [treasure-data/digdag#1267]
Support for podman will be great. Podman has compatibility with Docker and works with docker images too. So I am guessing implementation in digdag should be straight forward. 

> What is [Podman](https://podman.io/)? Podman is a daemonless container engine for developing, managing, and running OCI Containers on your Linux System. Containers can either be run as root or in rootless mode. Simply put: `alias docker=podman`.

**Comment by hiroyuki-sato** [comment]
Hello, @thejeshgn 

I'm not familiar with Podman. But, I think some features are developing in [v0_10](https://github.com/treasure-data/digdag/tree/v0_10) branch.
Could you check [this slide](https://www.slideshare.net/muga.nishizawa/custom-script-execution-environment-on-td-workflow-td-tech-talk-20181017) first?

@muga, @yoyama, Could you comment when you get a chance?

**Comment by ehaupt** [comment]
I would like to see this officially supported as `podman` can be run rootless. Since `podman` aims to be command compatible with `docker` this should technically work:

Global:

```yaml
_export:
  docker:
    image: "someimage:latest"
    docker: "/usr/bin/podman"
```

Or as per-task:

```yaml
+Example:
  docker:
    image: "someimage:latest"
    docker: "/usr/bin/podman"
  sh>: echo "I am running in a podman container"
```

Unfortunately that does not currently work very stable. I experience sporadic runtime failures even though the `podman` run does not fail.

I believe it has to do with the way `docker` (or in this case `podman`) is invoked here:

https://github.com/treasure-data/digdag/blob/011d848689ae3d31a8624d59bc8ece5c38e3ae5e/digdag-standards/src/main/java/io/digdag/standards/command/DockerCommandExecutor.java#L60-L79
