### ISSUE TITLE
When clicking a workflow in web UI, once displayed, it turns white. from v0.9.40

### ISSUE THREAD

**Issue by kjnh10** [treasure-data/digdag#1352]
When clicking a workflow in web UI, once the content displayed, it turns white page. from v0.9.40

This issue does not happen in v0.9.39.

If there is anything I can do, please let me know.

**Comment by hiroyuki-sato** [comment]
Hello, @kjnh10 

* Have you ever tried version 0.9.41?
* Could you tell me the reproduce steps?

I tried it the following way, But I can't reproduce it in my environment.

* macOS: 10.14.6
* digdag: 0.9.41
* Java: 1.8.0_192

## Testing steps.

```
digdag server -m
```

```
digdag init -t sh fuga
cd fuga
digdag push fuga
```

access: web UI
http://localhost:65432/projects/1/workflows/fuga
push run button

**Comment by kjnh10** [comment]
Thanks for you response, @hiroyuki-sato 

I have tried version 0.9.41, which has the same error.
The minimal step to reproduce is below.

1. launch server
![image](https://user-images.githubusercontent.com/6933428/73818879-a52cde80-4831-11ea-94d9-367aab92f3f9.png)

2. push test project
![image](https://user-images.githubusercontent.com/6933428/73819434-dce85600-4832-11ea-861e-d2e165b84f32.png)

3. open my broswer and click workflow.
![image](https://user-images.githubusercontent.com/6933428/73819779-a959fb80-4833-11ea-9e44-9874c209aae6.png)
![image](https://user-images.githubusercontent.com/6933428/73819887-d73f4000-4833-11ea-9520-7e1843c5f146.png)

Please note that I have tried some browsers(chrome, IE, firefox), the results are same.

My env info:
OS: windows 7
digdag:  0.9.41 (or 0.9.40)
java: 1.8.0_231

**Comment by hiroyuki-sato** [comment]
Hello, @kjnh10 

Thank you for reporting the issue.

I succeed to reproduce the issue in my environment.

I narrowed down the problem.

NG: white page

```yaml
+setup:
  echo>: start ${session_time}

_error:
  mail>:
    data: failed downloading
  subject: error-notification
```

OK: no white page

```yaml
+setup:
  echo>: start ${session_time}

_error:
  mail>:
#    data: failed downloading
  subject: error-notification
```

* macOS: 10.14.6
* digdag: 0.9.41
* Java: 1.8.0_192


@szyn Could you check this issue?
