### ISSUE TITLE
for_each with variables

### ISSUE THREAD

**Issue by send** [treasure-data/digdag#136]
On igdag v0.8.1, this code got an error with `Expected array type for key 'element' but got "[1,2,3,4]" (string)`. 

```yaml
timezone: UTC

_export:
  elements: [ 1, 2, 3, 4 ]

+main:
  for_each>:
    element: ${elements}
  _do:
    sh>: echo ${element}

```
How do I use for_each with variables?
