### ISSUE TITLE
How to run for_each tasks independently?

### ISSUE THREAD

**Issue by trendcloudservices** [treasure-data/digdag#1490]
I have a simple workflow:

```
schedule:
    daily>: 17:00:00

+generate:
    +repeat:
         for_each>:
             ns: [year-2015, year-2016, year-2017, year-2018, year-2019, year-2020]
             _do:
                 sh>: ${HOME}/scripts/generate.sh --ns ${ns}
```
I would like to run the task '`generate.sh`' independently, i.e. if one of the for loop year fails, the execution should keep continuing for rest of the tasks.

I tried `_parallel:true` , but that makes all the for loop tasks run parallely. I want them to run serially but failure of one task shouldn't halt the execution, and in the end, if one of the tasks fails the entire group should be tagged as failure after completion of all for each vars. How do I make it work?

**Comment by hiroyuki-sato** [comment]
Hello, @trendcloudservices 

Have you ever tried [`require>`](http://docs.digdag.io/operators/require.html#options) operator with `session_time` option?

```yaml
timezone: UTC

schedule:
  monthly>: 1,09:00:00

+depend_on_all_daily_workflow_in_month:
  loop>: ${moment(last_session_time).daysInMonth()}
  _do:
    require>: daily_workflow
    session_time: ${moment(last_session_time).add(i, 'day')}

# some monthly tasks here
```
