### ISSUE TITLE
SELinux with docker needs :Z volume mount option

### ISSUE THREAD

**Issue by ehaupt** [treasure-data/digdag#1663]
When using SELinux with docker, volumes should be mounted with the `:Z` [mount option](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label).

This is set here:

https://github.com/treasure-data/digdag/blob/07c11785b6f5c8c2469a94ec764e1d1a448be667/digdag-standards/src/main/java/io/digdag/standards/command/DockerCommandExecutor.java#L115-L116

When using SELinux, this should be:

```java
            command.add("-v").add(String.format(ENGLISH,
                        "%s:%s:rw,Z", projectPath, projectPath));  // use projectPath to keep pb.directory() valid
```

Maybe a config option could be introduced:

```yaml
_export:
  docker:
    image: "python:3.8-slim"
    pull_always: true
    selinux: true
```
