### ISSUE TITLE
[Feature Request] support `1h` for `_retry.interval`

### ISSUE THREAD

**Issue by seiyab** [treasure-data/digdag#1703]
I'm happy if `interval` in `_retry` supports syntax like `3h`, `30m` and so on.

```yaml
+task:
  _retry:
    limit: 3
    interval: 1h # <- suggestion
```

I think it can be realized using [`Durations.parseDuration`](https://github.com/yoyama/digdag/blob/8cfb0f92ef9975efecf8c9d7cea2635a5cbf7e34/digdag-plugin-utils/src/main/java/io/digdag/util/Durations.java#L16) in [`RetryControl`](https://github.com/treasure-data/digdag/blob/34f1f56f906399200937680f1eb9bd107241ebe4/digdag-plugin-utils/src/main/java/io/digdag/util/RetryControl.java#L69).
