### ISSUE TITLE
Slack notification not sent when error occurs

### ISSUE THREAD

**Issue by tanaka-yayoi** [treasure-data/digdag#1829]
If anyone has insights or experience with this issue, your assistance would be greatly appreciated.

**Description**
task.dig
```
!include : notice/error_notifier.dig

+task:
  td_run>: <query_id>
```

notice/error_notifier.dig
```
_export:
  plugin:
    repositories:
      - https://jitpack.io
    dependencies:
      - com.github.szyn:digdag-slack:0.1.4
  webhook_url: <slack webhook url>

_error:
  slack>: notice/danger-template.yml
```

The query executed with `td_run>:` is publishing results to Tableau Server using the "Export Results" feature. Errors in the task are caught by error_notifier.dig and a notification is sent to Slack using the plugin.

Due to an overlap with Tableau Server maintenance, an error occurred while publishing, but no error notification was sent to Slack. What's puzzling is that the error task is reported as successful in the Digdag Server logs.

**Reproduction Steps**
Reproduction has not been successful.

Tried the following, all of which were successfully notified:

- Causing an error using the `fail>:` operator
- Executing a deliberately failing query
- Specifying a non-existent project as the "Export Results" destination to induce failure

**Expected Behavior**
No cases where error notifications are not sent, or clarification of specific conditions under which error notifications are not sent.

**Environment**
Digdag version: 0.10.4
Plugin version: 0.1.4 ([digdag-slack](https://github.com/szyn/digdag-slack))
