### ISSUE TITLE
Offload project archive decompression to the browser instead of JS

### ISSUE THREAD

**Issue by cesarandreu** [treasure-data/digdag#420]
I think it's possible to remove gzip decompression from the JS side and let the browser handle it. That lets you drop `pako` as a dependency, which bundles a bunch of large crypto libs.

Currently, fetching a project archive looks like this:

```
Request:
  Accept: */*
  Accept-Encoding: gzip, deflate, sdch, br
  ...

Response:
  Content-Type: application/gzip
  ...
```

We can use the `Accept` header (or query param, separate endpoint, etc.) to signal that we want to let the browser inflate the response for us. According to [Wikipedia](https://en.wikipedia.org/wiki/List_of_archive_formats), `.tar` has a mime type of `application/x-tar`.  After the change it would look like this:

```
Request:
  Accept: application/x-tar
  Accept-Encoding: gzip, deflate, sdch, br
  ...

Response:
  Content-Type: application/x-tar
  Content-Encoding: gzip
  ...
```
