### ISSUE TITLE
[Tips] sh(Powershell) operator for Windows.

### ISSUE THREAD

**Issue by hiroyuki-sato** [treasure-data/digdag#474]
I'm not familiar with Windows environment. 
The following task worked fine on my Windows environment(Windows7 Professional).
This tips might be useful for a digdag user who is using Windows.

Please add a document if this tip is useful.

```yaml
timezone: UTC

_export:
  sh:
    shell: ["PowerShell.exe","-"]

+setup:
  sh>: echo "test"
```

Reference. (written in Japanese)
* [Qiita](http://qiita.com/yushimizu/items/ad785bc4c91539a58443)
* [Twitter](https://twitter.com/hiroysato/status/821336333545193474)
