### ISSUE TITLE
Using a list/array in mail operator

### ISSUE THREAD

**Issue by cosmok** [treasure-data/digdag#570]
Hi,
```
Digdag v0.9.12
```

I am unable to use an array from a variable in mail operator, for eg,:
```
cat fail_mail.dig 

_export:
   mail:
      from: "digdag@k7.local"
      host: localhost
      port: 2225
   emails:
     - 123@abc.com
     - 456@abc.com

+fail_mail:
  sh>: exit 1
  _error:
    mail>:
        data: workflow failed
    subject: this failed
    to: ${emails}

```
throws an error:
```
2017-05-26 11:52:27 +1000 [ERROR] (0016@[0:default]+fail_mail+fail_mail^error): Configuration error at task +fail_mail+fail_mail^error: Invalid address (config)
> Illegal address (address) 
```
If I use an YAML anchor it works as expected:

```
cat fail_mail_anchor.dig 

_export:
   mail:
      from: "digdag@k7.local"
      host: localhost
      port: 2225
   emails: &emails
     - 123@abc.com
     - 456@abc.com

+fail_mail_enchor:
  sh>: exit 1
  _error:
    mail>:
        data: workflow failed
    subject: this failed
    to: *emails

```

and just plain echo is outputting the array:
```
cat fail_echo.dig 

_export:
   mail:
      from: "digdag@k7.local"
      host: localhost
      port: 2225
   emails:
     - 123@abc.com
     - 456@abc.com

+fail_echo:
  sh>: exit 1
  _error:
    sh>: echo ${emails}

2017-05-26 12:03:01 +1000 [INFO] (0016@[0:default]+fail_echo+fail_echo^error): sh>: echo ["123@abc.com","456@abc.com"]

```

But, anchor is not an option(?) as I would like to add the emails to a separate files and include them in the _export section.
