### ISSUE TITLE
Proposal for for_range operator

### ISSUE THREAD

**Issue by frsyuki** [treasure-data/digdag#654]
We have a ETL workflow that needs to process approximately 300 million rows at a time. It is too big to process using one statement. Therefore, we want to divide it into multiple tasks using workflow.

Our current approach is this:

```yaml
# Fetch statistics of the source table
+count:
  td>: {data: select min(time) as min_time, max(time) as max_time, count(*) as count from src}
  store_last_results: true

# Divide it into 1 million rows
+loop:
  loop>: ${Math.ceil(td.last_results.count / 1000000.0)}
  _do:
    td>: etl_with_time_range.sql
    time_width: ${Math.max((max_time - min_time) / Math.ceil(td.last_results.count / 1000000.0), 1)}
    time_cond: |
      ${td.last_results.min_time + i * parseInt(time_width)} <= time
      AND time <${td.last_results.min_time + (i + 1) * parseInt(time_width)}
```

There are several problems with this approach.

* Workflow becomes complicated. It's hard to read.
* Calculation of ceil and max are tricky and easily lead bugs.
* If count is big, this loop creates too many tasks. It should add limitation on number of loop but adding such limitation makes the workflow even more complicated.

Proposal here is adding another operator to make it easy.
It can make the workflow much simpler:

```yaml
# Fetch statistics of the source table
+count:
  td>: {data: select min(time) as min_time, max(time) as max_time, count(*) as count from src}
  store_last_results: true

# Divide it into 1 million rows
+loop:
  # for the range of [min_time, max_time)
  for_range>:
    from: ${td.last_results.min_time}
    until: ${td.last_results.max_time + 1}
    # slice the range into this many chunks:
    count: ${Math.min(td.last_results.count / 1000000, 200)}  # at most 200 tasks
  # it loops for each chunk with `range.from` and `range.until` parameters set
  _do:
    td>: etl_with_time_range.sql
    time_cond: |
      ${range.from} <= time AND ${range.until} < time
```
