### ISSUE TITLE
Failed to update secret value when new-value is shorter than old-value.

### ISSUE THREAD

**Issue by cocodrips** [treasure-data/digdag#656]
Prepared 2 script.

**test.dig**
```yaml
timezone: UTC

+test_secret:
  _env:
    s: ${secret:secret_val}
  py>: tasks.secret_test.test
```

**tasks/secret_test.py**
```py
import digdag
import os

def test():
    print('secret_value:', os.environ.get('s'))
```

Set secret value and run workflow.
```sh
$ digdag secrets --local --set secret_val=12345
$ digdag run test.dig --rerun
```
output:
```
secret_value: 12345
```

Reset secret value and rerun workflow.
```sh
$ digdag secrets --local --set secret_val=67
$ digdag run test.dig --rerun
```
output:
```
secret_value: 67345
```
Failed to update value 12345 -> 67.

FYI:Success to update secret value after delete old-value.
