### ISSUE TITLE
A moment.js parameter which defined in export part,  cannot reference properly.

### ISSUE THREAD

**Issue by hiroyuki-sato** [treasure-data/digdag#678]
* Digdag 0.9.20

The `${nested.param2}` parameter can't extract moment.js result if it reference `_export` value. 

## 1. Test code

```yaml
_export:
  now: ${moment(session_time).utc().format('YYYY-MM-DD HH:mm:ss Z')}

+export_test:
  sh>: env
  param1: ${now}
  nested:
    param2: ${now}
```

### 1.1 Expected behavior

```
param1=2017-10-31 00:00:00 +00:00
nested={"param2":"2017-10-31 00:00:00 +00:00"}
```

### 1.2 Actual behavior

```
param1=2017-10-31 00:00:00 +00:00
nested={"param2":"${moment(session_time).utc().format('YYYY-MM-DD HH:mm:ss Z')}"} # <-- Can't extract
```

## 2. Test code2

It worked as I expected if I write moment.js script directly on nested.params2 .

```yaml
_export:
  now: ${moment(session_time).utc().format('YYYY-MM-DD HH:mm:ss Z')}

+export_test:
  sh>: env
  param1: ${now}
  nested:
    param2: ${now}

+param_test:
  sh>: env
  param1: ${moment(session_time).utc().format('YYYY-MM-DD HH:mm:ss Z')}
  nested:
    param2: ${moment(session_time).utc().format('YYYY-MM-DD HH:mm:ss Z')}
```

export_test result

```
param1=2017-10-31 00:00:00 +00:00
nested={"param2":"${moment(session_time).utc().format('YYYY-MM-DD HH:mm:ss Z')}"}
```

param_test result.

```
param1=2017-10-31 00:00:00 +00:00
nested={"param2":"2017-10-31 00:00:00 +00:00"}
```

## 3. Reference

* [Twitter](https://twitter.com/kazukgw/status/925018998307045378)
