### ISSUE TITLE
Issue when accessing `http.last_content` when making another `http>` operator call.

### ISSUE THREAD

**Issue by Xorso** [treasure-data/digdag#684]
We are currently making a call to a HTTP REST endpoint and storing the results and exporting to a variable. The issue occurs when it tries to evaluate that variable after making another http operator call.

```
+get_id:
  http> https://endpoint/env/Production
  store_content: true
  content_type: "applicication/json"

+create_host:
  _export:
    env_id: ${JSON.parse(http.last_content)[0].id}

    +export_host:
      http> http://endpoint/env/${env_id}/create/
       store_content: true
       content_type: "application/json"
    +print_job_status
      http> http://endpoint/env/${env_id}/${JSON.parse(http.last_content).id}
       store_content: true
       content_type: "application/json"
```

The issue is that the evaluation of +print_job_status fails because it tries to evaluate it based on the previous `${JSON.parse}`. Is there a way around this?

**Comment by hiroyuki-sato** [comment]
Hello @Xorso 
Have you ever tried `rb>` or `py>` operator?

```yaml
_export:
  rb:
    require: 'store'

+get_param:
  #
  # This operator will get the result
  # {"name":"bob","age":20}
  #
  +step1:
    http>: "http://localhost:4567/"
    store_content: true

  # set age and name parameter.
  +step2:
    rb>: MyWorkflow.step1

  # second query with first query result.
  +step3:
    #
    # This operator request 'http://localhost:4567/bob/20'
    #
    http>: http://localhost:4567/${name}/${age}
    store_content: true

  # set second parameter
  +step4:
    rb>: MyWorkflow.step2

  # echo first and second parameter
  +step5:
    echo>: ${msg} ${age}
```

```ruby
require 'json'

class MyWorkflow
  def step1
    http_result = JSON.parse(Digdag.env.params['http']['last_content'])

    Digdag.env.store(age: http_result['age'])
    Digdag.env.store(name: http_result['name'])
  end

  def step2
    http_result = JSON.parse(Digdag.env.params['http']['last_content'])

    Digdag.env.store(msg: http_result['msg'])
  end
end
```

See also: https://github.com/hiroyuki-sato/digdag-support/tree/master/core_684_http_param
