### ISSUE TITLE
require> checking multiple days.

### ISSUE THREAD

**Issue by Xorso** [treasure-data/digdag#685]
We are currently using the `require>` operator to check that another workflow was executed. We ran into an issue, however, where we were requiring it ran that same day but when the day rolled over and we executed the failed workflow with the require it kicked it off dependent workflow again. 

```yaml
+require_data_scrub:
  require>: data_scrub
  session_time: ${moment(session_time).format()}
```
Is it possible to require that was ran within the last 48 hours?

**Comment by hiroyuki-sato** [comment]
Hello, @Xorso 

Do those previous tasks run periodically?(hourly or something)
Have you ever tried `require>` with `loop>` operator?

The following example copied from 
https://docs.digdag.io/operators/require.html#options


```yaml
schedule:
  monthly>: 1,09:00:00

+depend_on_all_daily_workflow_in_month:
  loop>: ${moment(last_session_time).daysInMonth()}
  _do:
    require>: daily_workflow
    session_time: ${moment(last_session_time).add(i, 'day')}
```

**Comment by Xorso** [comment]
The required workflow runs once a week. and we just need to check if it was successful yesterday or today. So is that what I need to do with the loop?

**Comment by hiroyuki-sato** [comment]
Hello, @Xorso 

How about this?

```yaml
timezone: UTC

+today_and_yesterday:

  loop>: 2
  _do:
    require>: hoge
    session_time: ${moment().add(-1*i,'days').format('YYYY-MM-DD[T00:00:00+00:00]')}
    #session_time: ${moment().add(-1*i,'days').startOf('days')}
    # Workaround: this code return '2017-11-17T00:00:00.000Z' but I got the error
    # Invalid ISO time format: %s"2017-11-17T00:00:00.000Z" (json mapping)
    # So I format date by myself.

+test:
  echo>: hello
```
