### ISSUE TITLE
[feauture request] docker options to set credential to pull image from private registry

### ISSUE THREAD

**Issue by grezar** [treasure-data/digdag#763]
I request new docker options to pull image from private registry with credentials. 
It's like below.
```
_export:
  docker:
    - image: foo/bar
       auth:
         username: grezar
         password: P@55w0rd
```
OR

```
_export:
  docker:
    - image: foo/bar
       aws_auth:
         aws_access_key_id: $ECR_AWS_ACCESS_KEY_ID
         aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY
```
Digdag currently can't use variable in `_export:`, but maybe to implement this feature, it must be necessary due to using credentials.
