### ISSUE TITLE
Workdir of docker container is overwritten

### ISSUE THREAD

**Issue by David-Development** [treasure-data/digdag#854]
I'm trying to get my workflow up and running with digdag and docker. After starting the container, the workdir which is defined in the Dockerfile of the container gets overwritten. I can't seem to find a way to set the workdir properly.

Example Workflow:  
```yaml
timezone: UTC
_export:
  MINIO_HOST: "127.0.0.1:9001"
  MINIO_USERNAME: "minio"
  MINIO_PASSWORD: "minio"

+my_task_1:
  _workdir: "/usr/src/app"
  _export:
    docker:
      image: python:3
  for_each>:
    crawler: [abc, def]
  _do:
    sh>: pwd
```

The output is something like this: `/tmp/digdag-tempdir3664891302268477936/workspace/3_report_32_180_1070820252556486184`

My use-case is, that I have a work-flow that consists of multiple steps, each step is somewhat complex and has it's own docker container with it's own entrypoint and workdir. 

Another problem is, that I'm not sure how to pass intermediate results / data between steps or how to scale this application onto multiple servers (e.g. have multiple workers)? Is there any documentation on this that I missed? The documentation only says: 

> Tasks can run on local machine, distributed servers, or in a Docker container.

Thanks! I really like digdag.

**Comment by hiroyuki-sato** [comment]
Hello, @David-Development 

Due to security reason, Digdag isolates each task environment.
It has some limitation, and a similar question already posted.
It seems that your question related to #785.

**Comment by grezar** [comment]
Hi, @David-Development 
As far as I know, there isn't a way to avoid overriding workdir if you run docker by digdag.
You may use `sh>:` operator to run docker like below

```
timezone: UTC
_export:
  MINIO_HOST: "127.0.0.1:9001"
  MINIO_USERNAME: "minio"
  MINIO_PASSWORD: "minio"

+my_task_1:
  for_each>:
    crawler: [abc, def]
  _do:
    sh>: docker run --rm python:3 pwd
```
