### ISSUE TITLE
Support CC and BCC by mail> operator

### ISSUE THREAD

**Issue by kamikaseda** [treasure-data/digdag#886]
mail> operator supports only "TO".

It would be better to support "CC" and "BCC" even though "TO" can define multiple addresses.

**Comment by muga** [comment]
@kamikaseda Do you have any suggestions about definitions of `cc` and `bcc` options. What do you think that same definitions as `to` option' like following can fit with your and general use cases?

```yaml
+step1:
  mail>: body.txt
  subject: workflow started
  to: [me@example.com]
  cc: [me@example.com]
  bcc: [me@example.com]
```
