### ISSUE TITLE
Backfill sessions are not sequential after unpause

### ISSUE THREAD

**Issue by jaymed** [treasure-data/digdag#929]
When you pause/un-pause a workflow the backfill behavior switches to parallel backfill rather than the expected sequential backfill. For example, a workflow with a one minute interval schedule that is paused for 10 minutes will run 10 parallel sessions as soon as it is un-paused. In contrast, a backfill command with the count set to 10 will run those 10 backfill sessions sequentially. I believe the expected behavior is to run things sequentially by giving the un-pause/backfill operation a chance to properly cycle through all the session times that were missed. This seems to be a bug. The impact is that multiple jobs running in parallel fail due to resource dependencies.

Digdag server version: 0.9.31
Database: PostgreSQL
Log/archive storage: S3

**Comment by hiroyuki-sato** [comment]
Hello, @jaymed 

IIUC, Digdag execute backfilled tasks in parallel when digdag server un-pause. It's not a bug.
And also Digdag `backfill` command does not guarantee sequential. The current implementation just backfills it one by one.
If your task depends on another task. you may use [`require>`](http://docs.digdag.io/operators/require.html) operator like the below.

For example

```yaml
timezone: UTC

schedule:
  monthly>: 1,09:00:00

+depend_on_all_daily_workflow_in_month:
  loop>: ${moment(last_session_time).daysInMonth()}
  _do:
    require>: daily_workflow
    session_time: ${moment(last_session_time).add(i, 'day')}
```
