### ISSUE TITLE
[feature request] docker options to pull only once in a workflow

### ISSUE THREAD

**Issue by sonots** [treasure-data/digdag#943]
digdag has an option to do `docker pull` always on running a task.

```
_export:
  docker:
    image: ubuntu
    pull_always: true
```

But, `docker pull` once at beginning of the workflow is fine enough for some cases (most of cases for me).

I want such an option.

Also, I am glad such option works to pull a docker image once on each node in HA environment.
