### ISSUE TITLE
Mail command not using information stored in secrets

### ISSUE THREAD

**Issue by nickhall** [treasure-data/digdag#948]
I have set the digdag server's `mail.host` to localhost and `mail.port` to 25 using secrets, confirmed that they are set, and run the following workflow.

```
_error:
  mail>:
    data: Digdag failure alert test
  subject: "Digdag failure alert test"
  to: [my.email@address]

+failed_task:
  fail>: This task failed!
```

The error is triggered as expected, but the `+failure-alert-test^error` logs show this failure message:

> io.digdag.core.agent.OperatorManager: Configuration error at task +failure-alert-test^error: Parameter 'port' is required but not set (config)

The server is running digdag 0.9.30

**Comment by hiroyuki-sato** [comment]
Hello, @nickhall 

`mail.host` and `mail.port` does not use secrets. You just set it in dig file like the below.
You need to store a password in secrets.

```yaml
timezone: "Asia/Tokyo"

_export:
  mail:
    host: localhost
    port: 25
    from: alice@example.com

_error:
  mail>:
    data: Digdag failure alert test
  subject: "Digdag failure alert test"
  to: [bob@example.com]

+failed_task:
  fail>: This task failed!
```

**Comment by hiroyuki-sato** [comment]
This issue also may help.
https://github.com/treasure-data/digdag/issues/356#issuecomment-254782996

**Comment by nickhall** [comment]
Thank you. If that's true then the documentation needs to be updated as it lists these options under secrets.

https://docs.digdag.io/operators/mail.html

Is there no way to set project-wide mail options or do I have to include this in every single workflow?

**Comment by hiroyuki-sato** [comment]
Thank you for reporting the issue.
It seems that the document needs to update.

IIUC, You needs to include SMTP setting like the below. 


```
|-- configs
|   `-- smtp.dig
|-- test.dig
`-- test2.dig
```

```yaml
timezone: "Asia/Tokyo"

_export:
  !include : 'configs/smtp.dig'

_error:
  mail>:
    data: Digdag failure alert test
  subject: "Digdag failure alert test"
  to: [bob@example.com]

+failed_task:
  fail>: This task failed!
```

```yaml
mail:
  host: smtp.example.com
  port: 25
  from: alice@example.com
```

**Comment by hiroyuki-sato** [comment]
Hello, @nickhall 

I've been forgotten system configuration.
You can define SMTP setting in a system config file globally.

I confirmed sending an email with the following configuration.

digdag.conf

```
config.mail.host = smtp.example.com
config.mail.port = 25
```

smtp.dig

```yaml
timezone: "Asia/Tokyo"

_export:
  from: "alice@example.com"

_error:
  mail>:
    data: Digdag failure alert test
  subject: "Digdag failure alert test"
  to: [bob@example.com]

+failed_task:
  fail>: This task failed!
mail:
  host: smtp.example.com
  port: 25
  from: alice@example.com
```

In local mode

```
digdag run -c digdag.conf smtp.dig
```

In server mode

```
digdag server -c digdag.conf -m
digdag push smtptest 
digdag start smtptest smtp --session now
```

I'm not sure whether `config.mail.password` is valid or not. It's a sensitive parameter.

* config.mail.host: String
* config.mail.port: int
* config.mail.tls: Boolean, default: true
* config.mail.ssl: Boolean, default: false
* config.mail.debug: Boolean, default: false
* config.mail.username: String
* config.mail.password: String
* config.mail.from: String
* config.mail.subject: String

## Reference

https://github.com/treasure-data/digdag/blob/master/digdag-standards/src/main/java/io/digdag/standards/operator/MailOperatorFactory.java#L257-L264
https://github.com/treasure-data/digdag/blob/master/digdag-standards/src/main/java/io/digdag/standards/operator/MailOperatorFactory.java#L54-L55
